# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pushNotification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pushNotification
   
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'Alamofire'
 pod 'Firebase/Firestore'
 pod 'ObjectMapper'
 pod 'AlamofireObjectMapper'

end
